Repository mju-likelion/goodlogging-frontend, pull requests merged in 2022-08, with the labels that each got.

#22 refactor: 버튼 및 네비게이션 컴포넌트 분리
  src/components/Buttons/BackButton/backButton.module.scss
  src/components/Buttons/BackButton/index.jsx
  src/components/Buttons/Button/button.module.scss
  src/components/Buttons/Button/index.jsx
  src/components/Buttons/CompleteButton/completeButton.module.scss
  src/components/Buttons/CompleteButton/index.jsx
  src/components/Gnb/gnb.module.scss
  src/components/Gnb/index.jsx
  src/routes/MenuPage/index.jsx
  src/routes/MenuPage/menuPage.module.scss
  src/routes/MyChallengePage/index.jsx
  src/routes/MyChallengePage/myChallengePage.module.scss
  src/routes/SettingPage/index.jsx
  src/routes/SettingPage/settingPage.module.scss
  src/routes/SignupPage/index.jsx
Labels: UI

#23 Feature/signup page
  package-lock.json
  package.json
  src/components/Buttons/Button/button.module.scss
  src/components/Buttons/Button/index.jsx
  src/hooks/useInput.js
  src/routes/SignupPage/index.jsx
Labels: UI

#25 style: 백그라운드 박스 에니메이션
  src/App.js
  src/assets/pngs/cheers.png
  src/assets/pngs/medal.png
  src/assets/pngs/plant.png
  src/routes/CompletePage/completePage.module.scss
  src/routes/CompletePage/index.jsx
Labels: UI

#21 Feature/feed page
  src/App.js
  src/components/RankProgress.jsx
  src/components/rankProgress.module.scss
  src/routes/FeedPage/feedPage.module.scss
  src/routes/FeedPage/index.jsx
Labels: UI

#24 Feature/plogging doing
  public/img/menubar.png
  src/App.js
  src/routes/PloggingDoingPage/index.jsx
  src/routes/PloggingDoingPage/ploggingDoingPage.module.scss
  src/routes/PloggingDoingPage/progressBar.jsx
Labels: UI

#26 feat: 토글스위치
  src/components/Buttons/ToggleButton/index.jsx
  src/components/Buttons/ToggleButton/toggleButton.module.scss
Labels: UI

#28 Feature/axios
  .gitignore
  src/service/goodlogging/index.js
  src/util/axios.js
Labels: 기능

#31 Feature/login
  package-lock.json
  package.json
  src/hooks/useIsAuth.jsx
  src/index.js
  src/redux/authSlice.js
  src/redux/store.js
  src/routes/LoginPage/index.jsx
  src/routes/LoginPage/loginPage.module.scss
Labels: 기능

#32 Feature/login error
  package-lock.json
  package.json
  src/redux/authSlice.js
  src/routes/LoginPage/index.jsx
Labels: UI, 기능

#33 feat: get region name and coordinate
  public/index.html
  src/routes/PloggingDoingPage/index.jsx
  src/util/geolocation.js
Labels: 기능

#34 Feature/plogging
  src/redux/ploggingSlice.js
  src/redux/store.js
  src/routes/CompletePage/completePage.module.scss
  src/routes/CompletePage/index.jsx
  src/routes/MainPage/index.jsx
  src/routes/PloggingDoingPage/index.jsx
  src/service/goodlogging/index.js
  src/util/axios.js
Labels: 기능

#35 feat: send request when user want to change setting
  src/components/Buttons/CompleteButton/index.jsx
  src/routes/SettingPage/index.jsx
  src/service/goodlogging/index.js
Labels: 기능

#36 Feature/myinfo page
  package-lock.json
  package.json
  src/App.js
  src/routes/MainPage/index.jsx
  src/routes/MyinfoPage/index.jsx
  src/routes/MyinfoPage/myInfoPage.module.scss
Labels: 기능

#42 Feature/chart
  src/components/Buttons/ToggleButton/index.jsx
  src/components/Buttons/ToggleButton/toggleButton.module.scss
  src/routes/MainPage/Chart/index.jsx
  src/routes/MainPage/index.jsx
  src/service/goodlogging/index.js
Labels: UI, 기능

#41 feat: signup slider
  src/components/Slider/index.jsx
  src/components/Slider/slider.module.scss
  src/routes/SignupPage/index.jsx
  src/routes/SignupPage/signupPage.module.scss
  src/styles/base/_more.scss
Labels: UI
